CREATE TABLE CURSOS
(
  ID SERIAL NOT NULL,
  CURSO VARCHAR(50) NOT NULL, 
  DESCRICAO VARCHAR(100),
  PRIMARY KEY (ID)
);

CREATE TABLE USUARIOS
(
  ID SERIAL NOT NULL,
  NOME VARCHAR(100) NOT NULL, 
  CPF VARCHAR(14),
  RG VARCHAR(12), 
  ENDERECO VARCHAR(100),
  NUMERO INTEGER,
  COMPLEMENTO VARCHAR(20),
  CEP VARCHAR(10),
  BAIRRO VARCHAR(50),
  CIDADE VARCHAR(50),
  ESTADO VARCHAR(25), 
  TELEFONE VARCHAR(20), 
  CELULAR VARCHAR(20), 
  EMAIL VARCHAR(100),
  PRIMARY KEY (ID)
);

CREATE TABLE INSCRICAO
(
  ID SERIAL NOT NULL,
  IDUSUARIOS INTEGER REFERENCES USUARIOS (ID), 
  IDCURSOS INTEGER REFERENCES CURSOS (ID),
  PRIMARY KEY (ID)
);
